export const INIT_BLOG_LIST_SUCCESS = 'INIT_BLOG_LIST_SUCCESS';
export const INIT_BLOG_LIST_FAIL = 'INIT_BLOG_LIST_FAIL';
export const SHOW_BLOG_CONTENT = 'SHOW_BLOG_CONTENT';
export const SAVE_BLOG_SUCCESS = 'SAVE_BLOG_SUCCESS';
export const DELETE_BLOG = 'DELETE_BLOG';
export const SAVE_BLOG_COUNTER = 'SAVE_BLOG_COUNTER';