export const INIT_COMMENT_LIST_SUCCESS = 'INIT_COMMENT_LIST_SUCCESS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const LIKE_RESULT = 'LIKE_RESULT';